### ISSUE TITLE
public credentials

### ISSUE THREAD

**Issue by nikooo777** [kmcowan/fusionj#1]
Hey!

Just wanted to give you a heads up because your AWS credentials (whether still valid or not) are committed here:
https://github.com/kmcowan/fusionj/blob/022aabd95c49320e0d340aff58c9fb9e07e9d9ea/src/com/lucidworks/fusion/support/tests/S3Test.java

**Comment by kmcowan** [comment]
Thanks very much.  They're not valid, just samples.

**Comment by nikooo777** [comment]
good then :)
